### ISSUE TITLE
Version 2.16 of oga is yanked. Please update the dependency so I can use prawn-styled-text.

### ISSUE THREAD

**Issue by alexgizh** [blocknotes/prawn-styled-text#10]
https://github.com/blocknotes/prawn-styled-text/blob/b3771e1f3aed1cbd4d415ac196d5bb365ca93550/prawn-styled-text.gemspec#L20

**Comment by blocknotes** [comment]
Hey @alexgizh.
Thank you for the issue.
I have just changed the oga dependency to 2.15 (which is not yanked). I can't move to 3.x ATM.
I admit that I left this lib behind... but I hope to be able to work more on it in the near future.
