### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by brandoncc** [blocknotes/prawn-styled-text#11]
We are working on switching to Sidekiq Enterprise to take advantage of threading, and I just realized that this gem is not thread safe because it uses class instance variables. I am interested in taking a shot at reimplementing your logic without them (using an instance of `PrawnStyledText` instead of using the class instance). I don't see a test suite though, and I would need that to make sure I haven't broken anything. Is there a test suite that I am not seeing, or some trick you use?

Thanks!

**Comment by blocknotes** [comment]
Hi @brandoncc 
This component is outdated; I would like to refactor it but honestly I don't know when I'll be able to go on.
Times ago I started this PR: https://github.com/blocknotes/prawn-styled-text/pull/8
Regarding specs: yeah, I need to add them but in past I had some troubles checking the rendered output.
I hope to work more on this project soon.

**Comment by blocknotes** [comment]
FYI I started to prepare some specs, but it will take a while to reach a good coverage.

**Comment by brandoncc** [comment]
I actually wrote a basic behavior test myself last night 😂 I needed to refactor to be thread safe and wanted some reassurance that I hadn't broken anything. I like your unit tests as well, and think they both have value. [Here](https://github.com/brandoncc/prawn-styled-text/blob/master/test/test_prawn_styled_text.rb) is my test.

I was also able to [refactor](https://github.com/brandoncc/prawn-styled-text/commit/b6820cafc5529af3bd7d56557eb3f83ae66f9580) to use an instance rather than rely on the module. I haven't tested it thoroughly yet, but I think it is going to be fine.

**Comment by blocknotes** [comment]
> I actually wrote a basic behavior test myself last night 😂 I needed to refactor to be thread safe and wanted some reassurance that I hadn't broken anything. I like your unit tests as well, and think they both have value. [Here](https://github.com/brandoncc/prawn-styled-text/blob/master/test/test_prawn_styled_text.rb) is my test.

Thanks for sharing!
I like the idea of comparing the rendered output, I think I'll add similar tests also to my gem.
I'll try to see if I can do without extra gems, like just comparing the hashes of the generated file and the expected file or something similar.

> I was also able to [refactor](https://github.com/brandoncc/prawn-styled-text/commit/b6820cafc5529af3bd7d56557eb3f83ae66f9580) to use an instance rather than rely on the module. I haven't tested it thoroughly yet, but I think it is going to be fine.

Ook, just a comment after a fast check - about the part:

```
module Prawn
  class Document
  # ...
```

Make good tests because that class is already defined by Prawn gem, so you could have trouble there.

**Comment by brandoncc** [comment]
> I'll try to see if I can do without extra gems, like just comparing the hashes of the generated file and the expected file or something similar.

I thought about doing this too, but came across [this](https://stackoverflow.com/questions/4797307/compare-pdf-content-with-ruby) SO question. It seems there are some metadata differences in PDF files that may cause issues with that approach. The last comment on that page is how I found identikal.

> Make good tests because that class is already defined by Prawn gem, so you could have trouble there.

I'm very curious what issues you think this might cause? Ruby supports re-opening classes, and we are just adding a method. I can't think of any issue that would be caused here. Can you elaborate? I know you are using `.class_eval`, but I don't think that should be necessary?

---

Thanks for the feedback, I appreciate it. I hope that we can merge repos eventually, but I'm not sure if that can ever happen because I needed a different implementation of "dynamic" br tags than you implemented because I need to match the behavior of a browser. Maybe one day we can find a way to merge :-)

**Comment by blocknotes** [comment]
> I thought about doing this too, but came across [this](https://stackoverflow.com/questions/4797307/compare-pdf-content-with-ruby) SO question. It seems there are some metadata differences in PDF files that may cause issues with that approach. The last comment on that page is how I found identikal.

I made a try and it doesn't seem an issue for Prawn PDF, here is a first spec:
https://github.com/blocknotes/prawn-styled-text/blob/master/spec/integrations/basic_content_spec.rb

Perhaps some metadata could change when the producer is updated 🤔 but for now I'll try in this way.

> I'm very curious what issues you think this might cause? Ruby supports re-opening classes, and we are just adding a method. I can't think of any issue that would be caused here. Can you elaborate? I know you are using `.class_eval`, but I don't think that should be necessary?

Nevermind - I was thinking to some Rails warnings when a module/class is already defined but on second thought I suppose it's not a real issue if the Prawn pdf gem is always required first.

> Thanks for the feedback, I appreciate it. I hope that we can merge repos eventually, but I'm not sure if that can ever happen because I needed a different implementation of "dynamic" br tags than you implemented because I need to match the behavior of a browser. Maybe one day we can find a way to merge :-)

I agree that in cases like this one it's better to go on with a fork.
Also considering that I would like to apply a major refactoring (with breaking changes) of this gem at some point 😄
