### ISSUE TITLE
<br> tags insert an extra line

### ISSUE THREAD

**Issue by brandoncc** [blocknotes/prawn-styled-text#2]
First off, thanks for this awesome library. I have found what I believe to be a bug though. `<br>` tags should just drop the text to the next line, but it inserts a blank line between the text. Here is a sample prawn file, along with a screenshot of the product:

```ruby
require 'prawn'

Prawn::Document.generate("test_br.pdf)" do
  text "text\ntext\ntext"
end
```

<img width="959" alt="image" src="https://user-images.githubusercontent.com/543973/40088823-988e406c-585d-11e8-9456-f06ee00111fe.png">

And here is a test using your library:

(place this in examples/test.html)
```
test<br>test<br />test<br />
another line
```

and the output:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/543973/40088852-c4b76060-585d-11e8-95de-68d588f21579.png">

---

Your library has been a life saver in a project I am working on, but this is a deal breaker. Is there a way to fix this, or a recommended workaround?

I was able to figure out that removing the `\n` text content that is inserted gives me the "drop to the next line" functionality I need when there is only one `<br>`, but when there are two, it doesn't work properly, since it does need the `\n` on the second, third, etc consecutive new line.

Thanks again!

**Comment by brandoncc** [comment]
I think I am going to fork the project for now, using this `.traverse` method:

```ruby
  def self.traverse( nodes, context = [], &block )
    @@current_styled_traversal_level += 1

    nodes.each do |node|
      if node.is_a? Oga::XML::Text
        yield :text_node, node.text.delete( "\n\r" ), context

        if node.text.strip.length.positive?
          puts "printed text:"
          p node.text.strip
          @@previous_styled_sibling_element_types[@@current_styled_traversal_level] = "text"
        end
      elsif node.is_a? Oga::XML::Element
        element = { name: node.name.to_sym, node: node }
        yield :opening_tag, element[:name], element
        context.push( element )
        traverse( node.children, context, &block ) if node.children.count > 0
        yield :closing_tag, element[:name], context.pop

        puts "closing #{element[:name]}"
        puts "#{element[:name]} follows block element" if BLOCK_TAGS.include?(@@previous_styled_sibling_element_types[@@current_styled_traversal_level])
        @@previous_styled_sibling_element_types[@@current_styled_traversal_level] = element[:name]
      end
    end

    @@current_styled_traversal_level -= 1
  end
```

If I run this HTML through it:

```html
test<br>test<br><br>test

<p>
  <span>
    test
  </span>
  <br>
  test 2
  <br>
</p>
<br>
```

The command line output is:

```
printed text:
"test"
closing br
printed text:
"test"
closing br
closing br
br follows block element
printed text:
"test"
printed text:
"test"
closing span
closing br
printed text:
"test 2"
closing br
closing p
closing br
br follows block element
```

Which is perfect. Now I will be able to output either `"\n"` or `''` as the text content for the closing `<br>` tag. That will allow me to handle them properly. If the tag follows a block level element, it should insert a text node with `"\n"`. If it doesn't, it should insert one with `''`.

If this sounds like something you would like me to submit a PR for, let me know. If we do that, I will add a configuration flag which is off by default so that users have to opt-in to use it, rather than breaking existing user's projects.

**Comment by brandoncc** [comment]
In case you are curious how it turned out, [this is my commit](https://github.com/brandoncc/prawn-styled-text/commit/b49eab50b9ba76d5dc859333b0c8b2022c8a2af4)

**Comment by blocknotes** [comment]
Hi @brandoncc 
Sorry for replying so late.
I have just prepared a small fix for the <br> tag, in master branch (not in gem for now, need more checks). It's a simple solution but it should work.

**Comment by blocknotes** [comment]
Hi @brandoncc
Sorry for replying so late. Thank you for reporting this problme.
I have just prepared a small fix for the 
tag, in master branch (not in gem for now, need more checks). It's a simple solution but it should work.

**Comment by blocknotes** [comment]
Hi @brandoncc
Sorry for replying so late. Thank you for reporting this problem.
I have just prepared a small fix for the 
tag, in master branch (not in gem for now, need more checks). It's a simple solution but it should work.

**Comment by blocknotes** [comment]
Hi @brandoncc
Sorry for replying so late. Thank you for reporting this problme.
I have just prepared a small fix for the BR tag, in master branch (not in gem for now, need more checks). It's a simple solution but it should work.

**Comment by brandoncc** [comment]
Thanks for getting back to me @blocknotes. Did you happen to look at my fix implementation? Since `<br>` tags respond differently based on whether they follow a block-level element or not, your fix does not replicate the browser output.

I used this test code on both of our fixes, as well as in Firefox and Chrome:

```html
<div>
  <span>This is a test</span>
  <br>
  <p>This is a test<br></p>
  <br><br>This is a test
  <p><br>This is a test</p>
</div>
```

Here is the result:

![screenshot](https://bc-screenshots.s3.amazonaws.com/Mozilla_Firefox_2018-06-28_13-56-18.png)

As you can see my fix is very close, but not quite exactly the same. That is because of the browser default margin on the final `<p>` tag (the first `<p>` margin gets swallowed by the `<br>`). As soon as I disable that margin, the output in Chrome is:

![screenshot](https://bc-screenshots.s3.amazonaws.com/dynamic_br.html_2018-06-28_14-00-53.png)

This is identical to my fix output.

I like that your implementation is simpler, but I started at the same place and figured out more was needed. What do you think about merging my fix? If you don't want to do that, maybe it will at least be of some help as a reference.

**Comment by blocknotes** [comment]
I understand your point but you are reporting another problem which is only partially BR-related, the default margins of the elements, and that should be managed in another way.
My library is not an HTML to PDF tool, it offers only a basic support for some HTML tags and attributes in a simple way. You can find a lot of different behaviors from browser rendering from my component.
I would like to do a major rewrite of this gem, so for now it's fine in this way for me.
Thank you for the proposed solution, I keep this Issue open for reference.

**Comment by brandoncc** [comment]
I think you are mistaken. I do not expect the gem to do anything with margin. My solution handles the fact that the br should act different based on whether it follows a block level element, yours does not. That is what I was showing you. Thank you for your time, I will continue to use my fork which handles it properly (and does not do anything with margins, I wouldn't want the gem to do anything with those in the way a browser does).

**Comment by blocknotes** [comment]
We have simply 2 different point of views; the solution I would like to implement (but that I can't apply now) is to handle the display attribute of each element correctly so your changes would only patch a specific case, this is not what I want to do now in my component otherwise I should add a lot of customized behaviors to achieve a better rendering for other elements.

**Comment by brandoncc** [comment]
Okay, my apologies. I thought you misunderstood what I was saying. I thought you were saying that I was asking you to handle margin/padding spacing. I didn't want any special rendering, only the correct behavior. With the exception of this issue, everything works great so thanks for making this gem! With my fix, it works perfectly for me 👍
