### ISSUE TITLE
Add support for <img> from external source

### ISSUE THREAD

**Issue by derUli** [blocknotes/prawn-styled-text#7]
My images are stored on an AWS storage and referenced by URL.
Unfortunately prawn-styled-text supports only local files as image source.
I had to download the images from AWS to temp files and to replace the URLs because it couldn't find the files.

Please add support for using images from http:// and https:// URLs

**Comment by CamiMeneses** [comment]
You can use:
require 'open-uri'
pdf = Prawn::Document.new
pdf.image open('your url here')
